export const purchaseOrderSchema = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    supplierId: { type: 'string' },
    branchId: { type: 'string' },
    buyerId: { type: 'string' },
    approverId: { type: ['string', 'null'] },
    status: { type: 'string', enum: ['Draft', 'Submitted', 'Approved', 'Fulfilled', 'Cancelled'] },
    totalExpectedAmount: { type: 'number' },
    submittedAt: { type: ['string', 'null'] },
    approvedAt: { type: ['string', 'null'] },
    fulfilledAt: { type: ['string', 'null'] },
    cancelledAt: { type: ['string', 'null'] },
    createdAt: { type: 'string' },
    updatedAt: { type: 'string' },
    lineItems: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          purchaseOrderId: { type: 'string' },
          productId: { type: 'string' },
          description: { type: 'string' },
          quantity: { type: 'number' },
          expectedUnitPrice: { type: 'number' },
          expectedTotalPrice: { type: 'number' },
          createdAt: { type: 'string' },
          updatedAt: { type: 'string' },
        },
        required: ['productId', 'quantity', 'expectedUnitPrice'],
      },
    },
  },
  required: ['id', 'supplierId', 'branchId', 'buyerId', 'status', 'totalExpectedAmount', 'lineItems'],
};
